---
- name: System Setup
  hosts: node1
  become: true
  tasks:
    - name: Update all security-related package
      ansible.builtin.dnf:
        name: '*'
        state: latest
        security: true
   
    - name: Create a new user
      ansible.builtin.user:
        name: djuser
        state: present
        create_home: true
